### ISSUE TITLE
porque al final de la ruta al realizar una solicitud agrega el símbolo `?`

### ISSUE THREAD

**Issue by GusGyoCode** [atomic-state/http-react#164]
Tengo una pregunta, porque al hacer una peticion y colocar la ruta al final de la ruta me agrega el simbolo `?`, por ejemplo tengo la consulta 
```
const { reFetch } = useFetch('https://pokeapi.co/api/v2/pokemon/bulbasaur', {
    auto: false,
    method: 'GET',
    onResolve (data) {
      console.log(data)
    },
    onError (err) {
      console.log(err)
    }
  })
```
y en la ruta que aparece en el navegador es 
`https://pokeapi.co/api/v2/pokemon/bulbasaur?` o `https://pokeapi.co/api/v2/pokemon/bulbasaur/?`
y al agregar ese simbolo hay rutas que me da error porque ese no es el path de la ruta 

hay forma de quitar ese simbolo al hacer la peticion?

**Comment by danybeltran** [comment]
Hola, este issue ha sido resuelto con este pull request:  https://github.com/atomic-state/http-react/pull/165

**Comment by GusGyoCode** [comment]
genial! gracias por la info! 😁

> Hola, este issue ha sido resuelto con este pull request: #165
